# Azure Pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cmake CMakeLists.txt
    cmake --build .
  displayName: 'Building...'

- script: lscpu
  displayName: 'CPU Info...'

- script: |
    ./Superquad
    ./Superquad 4
    ./Superquad 8 1000
    ./Superquad 8 1000 output.csv
    ./Superquad 8 1000 -vol just_volumes.csv
  displayName: 'Running binary...'

- publish: $(System.DefaultWorkingDirectory)/records.csv
  artifact: records.csv
